apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: upload-s3-object
inputs:
  file-path:  # id of input
    description: 'Local File Path'
    required: true
  bucket-name:  # id of input
    description: 'bucket name'
    required: true
  s3-path:  # id of input
    description: 's3 path containing object'
    required: true
runs:
  using: composite
  steps:
    - id: s3-action-upload
      name: s3-action-upload
      uses: docker://amazon/aws-cli
      shell: bash
      run: |
        set -x

        bucketname="${{ inputs.bucket-name }}"
        s3path="${{ inputs.s3-path }}"

        s3uri="$bucketname"

        # if bucketname does not have s3:// prefix 
        if [[ $bucketname != s3://* ]]; then
           bucketname="s3://$bucketname"
        fi 

        #if s3path does not start with /
        if [[ $s3path != /* ]]; then
           s3path="/$s3path"
        fi 
        
        # final s3url
        s3uri="$bucketname$s3path"

        echo $s3uri

        if [ -f ${{ inputs.file-path }} ]; then
          aws s3 cp ${{ inputs.file-path }} $s3uri | tee "${{cloudbees.workspace}}/aws_response.txt"
        elif [ -d ${{ inputs.file-path }} ]; then
          aws s3 cp ${{ inputs.file-path }} $s3uri --recursive | tee "${{cloudbees.workspace}}/aws_response.txt"
        fi 
        grep upload: "${{cloudbees.workspace}}/aws_response.txt" | sed 's/.*upload: //' | awk '{print "| " $1 " | " $3 " |"}' | tee "$CLOUDBEES_OUTPUTS/s3_upload_evidence"
    
    - name: publish-evidence
      uses: cloudbees-io/publish-evidence-item@v1
      with:
        content: |-
          # S3 Upload results
          | Local file | S3 |
          | ---- | ---- |         
          ${{ steps.s3-action-upload.outputs.s3_upload_evidence }}

