= CloudBees action: Store an object on Amazon S3

Use this action to upload an object file to Amazon Simple Storage Service (Amazon S3).

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `bucket-name`
| String
| Yes
| The Amazon S3 bucket name.

| `file-path`
| String
| Yes
| The local file path of the object to be uploaded.

| `s3-path`
| String
| Yes
| The Amazon S3 destination path for the upload.

| `send-artifact-info`
| String
| No
| If set to `true`, publishes artifact information to CloudBees Platform.

| `artifact-name`
| String
| No
| If `send-artifact-info` is `true`, specify the name of the artifact. If not provided, the file name/folder name is used.

| `artifact-version`
| String
| No
| If `send-artifact-info` is `true`, specify the version of the artifact. If not provided, a default value of `-` is used.

|===

== Usage example

In your YAML file, add:

[source,yaml]
----

      - name: Upload to Amazon S3
        uses: cloudbees-io/s3-upload-object@v1
        with:
          file-path: "/local-image.tar"
          bucket-name: "Amazon_S3_bucket_name"
          s3-path: "amazon-s3-image.tar"
          send-artifact-info: "false"
----

If you want to publish build artifact information, set `send-artifact-info` to `true` and optionally provide `artifact-name` and `artifact-version`:

[source,yaml]
----
      - name: Upload to Amazon S3 with Artifact Info
        uses: cloudbees-io/s3-upload-object@v1
        with:
          file-path: "/local-image.tar"
          bucket-name: "Amazon_S3_bucket_name"
          s3-path: "amazon-s3-image.tar"
          send-artifact-info: "true"
          artifact-name: "my-artifact-name"  # Optional, defaults to the file name if not provided
          artifact-version: "1.0.0"  # Optional, defaults to "-" if not provided
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
