= CloudBees action: Store an object on Amazon S3

Use this action to upload an object file to Amazon Simple Storage Service (Amazon S3). This action also reports artifact related data to the workflow run for artifact traceability purposes.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `bucket-name`
| String
| Yes
| The Amazon S3 bucket name.

| `file-path`
| String
| Yes
| The local file path of the object to be uploaded.

| `s3-path`
| String
| Yes
| The Amazon S3 destination path for the upload.

| `send-artifact-info`
| String
| No
| Enable to send artifact information to the Cloudbees Platform for artifact traceability purposes.

| `artifact-name`
| String
| No
| The name of the artifact to send to the Cloudbees Platform for artifact traceability purposes.

| `artifact-version`
| String
| No
| The version of the artifact to send to the Cloudbees Platform for artifact traceability purposes.

|===

== Outputs

[cols="2a,2a,5a",options="header"]
.Output details
|===

| Output name
| Data type
| Description

| `artifact-id`
| String
| The unique identifier of the artifact.

|===

== Usage example

In your YAML file, add:

[source,yaml]
----

      - name: Upload to Amazon S3
        uses: cloudbees-io/s3-upload-object@v1
        with:
          file-path: "/local-image.tar"
          bucket-name: "Amazon_S3_bucket_name"
          s3-path: "amazon-s3-image.tar"
          send-artifact-info: "false"
----

If you want to publish build artifact information, set `send-artifact-info` to `true` and optionally provide `artifact-name` and `artifact-version`:

[source,yaml]
----
      - name: Upload to Amazon S3 with Artifact Info
        uses: cloudbees-io/s3-upload-object@v1
        with:
          file-path: "/local-image.tar"
          bucket-name: "Amazon_S3_bucket_name"
          s3-path: "amazon-s3-image.tar"
          send-artifact-info: "true"
          artifact-name: "my-artifact-name"  # Optional, defaults to the file name if not provided
          artifact-version: "1.0.0"  # Optional, defaults to "-" if not provided
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
